// src/utils/seedData.js
// Call seedInternships(companyUserId) once to populate Firestore with fake data.

import { collection, addDoc, serverTimestamp, getDocs, query, where } from 'firebase/firestore';
import { db } from '../firebase/config';

const FAKE_INTERNSHIPS = [
  {
    title: 'Frontend Developer Intern',
    companyName: 'Stripe',
    domain: 'Engineering',
    workType: 'Remote',
    location: 'Remote',
    duration: 2,
    isPaid: true,
    stipend: 12000,
    openings: 3,
    description: 'Work with our frontend team to build beautiful, performant UI components using React and TypeScript. You will contribute to real production features used by millions of users worldwide.',
    responsibilities: 'Build reusable React components\nWrite unit and integration tests\nCollaborate with designers on UI implementation\nOptimize performance of existing components',
    requirements: 'Strong knowledge of React.js\nFamiliarity with TypeScript\nUnderstanding of CSS and responsive design\nGit version control',
    perks: 'Letter of Recommendation\nCertificate of Completion\nPre-Placement Offer opportunity',
    skills: ['React', 'TypeScript', 'CSS', 'Git'],
    applicationDeadline: '2026-10-30',
    status: 'active',
    applicantsCount: 24,
  },
  {
    title: 'Product Design Sprint',
    companyName: 'Notion',
    domain: 'Design',
    workType: 'Hybrid',
    location: 'New York',
    duration: 1,
    isPaid: true,
    stipend: 8000,
    openings: 2,
    description: 'Join Notion\'s design team for a focused 4-week sprint. You\'ll work on redesigning key product flows and creating high-fidelity prototypes.',
    responsibilities: 'Create wireframes and prototypes in Figma\nConduct user research interviews\nPresent design concepts to stakeholders',
    requirements: 'Proficiency in Figma\nBasic understanding of UX principles\nPortfolio of previous design work',
    perks: 'Certificate\nLOR\nNetworking opportunities',
    skills: ['Figma', 'Prototyping', 'UX Research', 'User Testing'],
    applicationDeadline: '2026-11-15',
    status: 'active',
    applicantsCount: 18,
  },
  {
    title: 'Data Science Intern',
    companyName: 'Razorpay',
    domain: 'Data Science',
    workType: 'Remote',
    location: 'Remote',
    duration: 3,
    isPaid: true,
    stipend: 15000,
    openings: 2,
    description: 'Analyze large-scale payment datasets to derive business insights and build predictive models.',
    responsibilities: 'Analyze payment transaction data\nBuild ML models for fraud detection\nCreate dashboards using Python/Tableau',
    requirements: 'Python (pandas, scikit-learn, numpy)\nSQL knowledge\nStatistics fundamentals',
    perks: 'Stipend + bonus\nPPO opportunity\nCertificate',
    skills: ['Python', 'SQL', 'Machine Learning', 'Statistics'],
    applicationDeadline: '2026-10-20',
    status: 'active',
    applicantsCount: 31,
  },
  {
    title: 'Growth Marketing Intern',
    companyName: 'Linear',
    domain: 'Marketing',
    workType: 'Remote',
    location: 'Remote',
    duration: 2,
    isPaid: true,
    stipend: 6000,
    openings: 1,
    description: 'Help Linear grow its developer community through content marketing, SEO, and social campaigns.',
    responsibilities: 'Plan and execute content campaigns\nWrite SEO-optimized blog posts\nManage social media presence',
    requirements: 'Understanding of SEO fundamentals\nExcellent writing skills\nFamiliarity with analytics tools',
    perks: 'Certificate\nLOR\nRemote flexibility',
    skills: ['SEO', 'Content Writing', 'Analytics', 'Social Media'],
    applicationDeadline: '2026-11-01',
    status: 'active',
    applicantsCount: 12,
  },
  {
    title: 'Backend Engineering Intern',
    companyName: 'Vercel',
    domain: 'Engineering',
    workType: 'Remote',
    location: 'Remote',
    duration: 3,
    isPaid: true,
    stipend: 18000,
    openings: 2,
    description: 'Build scalable Node.js APIs and microservices that power Vercel\'s edge deployment platform.',
    responsibilities: 'Design and build REST/GraphQL APIs\nWrite tests for backend services\nOptimize database queries',
    requirements: 'Node.js / Express experience\nDatabase knowledge (PostgreSQL or MongoDB)\nUnderstanding of REST APIs',
    perks: 'High stipend\nPPO\nCertificate\nGlobal team exposure',
    skills: ['Node.js', 'PostgreSQL', 'Docker', 'REST APIs'],
    applicationDeadline: '2026-12-01',
    status: 'active',
    applicantsCount: 45,
  },
  {
    title: 'UI/UX Design Intern',
    companyName: 'Hashnode',
    domain: 'Design',
    workType: 'Remote',
    location: 'Remote',
    duration: 2,
    isPaid: false,
    stipend: 0,
    openings: 1,
    description: 'Redesign key developer-facing features on Hashnode\'s blogging platform.',
    responsibilities: 'Conduct UX audits of existing features\nCreate wireframes and hi-fi mockups\nPrepare design handoffs for developers',
    requirements: 'Figma proficiency\nPortfolio required\nBasic HTML/CSS knowledge a plus',
    perks: 'Certificate\nLOR\nPublic portfolio piece',
    skills: ['Figma', 'UI Design', 'Wireframing', 'CSS'],
    applicationDeadline: '2026-10-25',
    status: 'active',
    applicantsCount: 9,
  },
  {
    title: 'Finance Analyst Intern',
    companyName: 'ClearTax',
    domain: 'Finance',
    workType: 'On-site',
    location: 'Bangalore',
    duration: 2,
    isPaid: true,
    stipend: 10000,
    openings: 3,
    description: 'Support the finance team with financial modeling, reporting, and analysis.',
    responsibilities: 'Prepare financial models in Excel\nAssist with monthly MIS reports\nAnalyze revenue and cost data',
    requirements: 'Commerce or Finance background\nStrong Excel skills\nBasic accounting knowledge',
    perks: 'Stipend\nCertificate\nFull-time opportunity',
    skills: ['Excel', 'Financial Modeling', 'Accounting', 'MS Office'],
    applicationDeadline: '2026-11-10',
    status: 'active',
    applicantsCount: 20,
  },
  {
    title: 'Content Strategy Intern',
    companyName: 'BrowserStack',
    domain: 'Content Writing',
    workType: 'Remote',
    location: 'Remote',
    duration: 1,
    isPaid: true,
    stipend: 5000,
    openings: 2,
    description: 'Create technical content for developers — tutorials, case studies, and documentation.',
    responsibilities: 'Write technical blog posts and tutorials\nResearch developer topics\nOptimize content for SEO',
    requirements: 'Strong technical writing skills\nFamiliarity with web development concepts\nSEO knowledge',
    perks: 'Certificate\nLOR\nPublished byline',
    skills: ['Technical Writing', 'SEO', 'Research', 'Content Strategy'],
    applicationDeadline: '2026-10-15',
    status: 'active',
    applicantsCount: 7,
  },
  {
    title: 'Mobile App Developer Intern',
    companyName: 'CRED',
    domain: 'Engineering',
    workType: 'Hybrid',
    location: 'Bangalore',
    duration: 3,
    isPaid: true,
    stipend: 20000,
    openings: 2,
    description: 'Build features for CRED\'s React Native mobile app used by millions of premium credit card users.',
    responsibilities: 'Develop React Native features\nIntegrate REST APIs\nWrite automated tests',
    requirements: 'React Native or Flutter experience\nJavaScript/TypeScript proficiency\nAPI integration knowledge',
    perks: 'Highest stipend\nPPO\nCertificate\nOn-site perks',
    skills: ['React Native', 'JavaScript', 'TypeScript', 'REST APIs'],
    applicationDeadline: '2026-12-15',
    status: 'active',
    applicantsCount: 52,
  },
  {
    title: 'HR Operations Intern',
    companyName: 'Zepto',
    domain: 'HR',
    workType: 'On-site',
    location: 'Mumbai',
    duration: 2,
    isPaid: true,
    stipend: 7000,
    openings: 1,
    description: 'Support Zepto\'s fast-growing HR team in recruitment coordination, onboarding, and employee engagement.',
    responsibilities: 'Screen and shortlist resumes\nCoordinate interview scheduling\nAssist with onboarding documentation',
    requirements: 'MBA HR or relevant degree\nExcel and Google Sheets proficiency\nStrong interpersonal skills',
    perks: 'Certificate\nLOR\nFull-time opportunity',
    skills: ['Recruitment', 'Excel', 'Communication', 'HR Operations'],
    applicationDeadline: '2026-11-20',
    status: 'active',
    applicantsCount: 15,
  },
];

export const seedInternships = async (companyUserId) => {
  if (!companyUserId) {
    console.error('Pass a company user ID');
    return;
  }
  const existing = await getDocs(query(
    collection(db, 'internships'),
    where('companyId', '==', companyUserId)
  ));
  if (!existing.empty) {
    console.log('Already seeded for this company.');
    return;
  }
  for (const data of FAKE_INTERNSHIPS) {
    await addDoc(collection(db, 'internships'), {
      ...data,
      companyId: companyUserId,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    });
  }
  console.log('✅ Seeded 10 internships');
};